print("Hello World")
print("First Hello World")
print("Second Hello World")
print("Third Hello World")
print("Fourth Hello World")
print("Fifth Hello World")
print("Sixth Hello World")
print("Seventh Hello World")
print("Eighth Hello World")
print("Ninth Hello World")
